[project]
name = "modern-llms"
version = "0.1.0"
description = "Implementation of modern LLM architectures."
readme = "README.md"
requires-python = "==3.12.11"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit==4.6.0",
    "ruff==0.15.22",
    "ty==0.0.60",
]

[tool.uv]
package = true

[tool.setuptools]
packages = ["src"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff]
line-length = 100
