_target_: src.model.llama.CustomLLaMAConfig
vocab_size: 32000
dim: 768
num_layers: 12
num_heads: 12
num_kv_heads: 4
hidden_ff: null
multiple_of: 256
norm_eps: 1e-5
rope_theta: 500000.0
max_seq_len: 1024
original_max_seq_len: null
tie_embeddings: true
initializer_range: 0.02
